//! Assemble the throwaway `target/dev/OpenLogi.app` that `cargo run -p
//! openlogi-desktop` launches.
//!
//! A bare `target/debug/openlogi-desktop` has no `Info.plist` and no
//! `Resources`, so macOS falls back to the executable name and a generic icon,
//! registers no `openlogi://` handler, and gives TCC nothing stable to key a
//! grant to. Wrapping the build in a real bundle fixes all four — and doing it
//! here rather than in the cargo runner means the dev and shipped bundles are
//! assembled by the same code: one identity table ([`identity::Channel`]), one
//! helper table ([`HELPERS`]), one set of `Info.plist` templates. The
//! two used to be separate implementations, which is how the dev overlay ended
//! up with no icon and the dev identity had to be renamed twice.
//!
//! The runner keeps only what must stay cheap: it is invoked for every binary
//! of every `cargo run`/`test`/`bench`, and everything but `openlogi-desktop`
//! is a passthrough that must not pay for an interpreter start.

mod processes;
mod signing;

use std::path::{Path, PathBuf};

use anyhow::{Context as _, Result, bail};
use clap::Parser;
use strum::VariantArray as _;
use xshell::{Shell, cmd};

use super::bundle::identity::{self, Channel, Component};
use super::bundle::{HELPERS, Helper};
use crate::icon::IconPipeline as _;
use crate::icon::macos::AppBundle;
use crate::support::fs::{ensure_file, repo_root};

/// The dev bundle is the dev bundle; there is no channel to choose.
const CHANNEL: Channel = Channel::Dev;

/// The app's own `Info.plist` template. The shipped app's is generated by
/// `cargo-bundle` from `Cargo.toml`, so this is the only checked-in one; like
/// the helpers' it carries no identity of its own — [`identity::stamp`] writes
/// it.
const APP_PLIST: &str = "crates/openlogi-desktop/bundle/desktop-dev/Info.plist";

/// The shared app icon, compiled by [`AppBundle`] alongside the catalog and
/// the alternates. Only this one is checked in; the rest a fresh clone
/// compiles on its first bundle.
const ICON: &str = "crates/openlogi-desktop/icon/AppIcon.icns";

/// What the identity pass covers when the helpers were not embedded.
const APP_ONLY: [Component; 1] = [Component::App];

#[derive(Parser)]
pub(crate) struct Args {
    /// The freshly built `openlogi-desktop` to wrap. Its parent directory also
    /// names the profile the helpers are built in, so the bundle never mixes a
    /// release GUI with a debug agent.
    #[arg(long)]
    binary: PathBuf,
}

pub(crate) fn run(args: &Args) -> Result<()> {
    let root = repo_root()?;
    let app = root.join("target/dev/OpenLogi.app");
    let profile = Profile::of(&args.binary)?;

    processes::reap_leftovers(&app, &root.join("target"))?;

    AppBundle.compile()?;
    let icon = root.join(ICON);
    ensure_file(&icon)?;

    let signing = signing::resolve(&app)?;
    fs_err::create_dir_all(app.join("Contents/MacOS"))?;
    fs_err::create_dir_all(app.join("Contents/Resources"))?;
    place_binary(
        &args.binary,
        &app.join("Contents/MacOS/openlogi-desktop"),
        &signing,
    )?;
    fs_err::copy(root.join(APP_PLIST), app.join("Contents/Info.plist"))
        .context("could not write the dev app Info.plist")?;
    fs_err::copy(&icon, app.join("Contents/Resources/AppIcon.icns"))?;
    AppBundle.install(&app)?;

    // Clear the whole login-items directory rather than the bundles about to be
    // written: helper directory names have changed more than once, and a
    // leftover from an older checkout is a second row in every macOS list that
    // names these processes.
    remove_bundle(&app.join("Contents/Library/LoginItems"))?;
    let components = if helpers_wanted() {
        for helper in &HELPERS {
            embed_helper(&root, &app, &profile, helper, &icon, &signing)?;
        }
        Component::VARIANTS
    } else {
        println!("==> helpers: skipped (OPENLOGI_DEV_AGENT=0)");
        &APP_ONLY
    };

    // Identity first, then the checks, then signing — a signature seals the
    // `Info.plist` files, so nothing may rewrite them afterwards.
    identity::stamp(&app, CHANNEL, components)?;
    identity::verify(&app, CHANNEL, components)?;
    identity::verify_icons(&app, CHANNEL, components)?;
    AppBundle.verify(&app)?;
    signing.run(&sign_order(&app, components))?;
    register_with_launch_services(&app)?;

    println!("Dev bundle ready: {}", app.display());
    Ok(())
}

/// Build one helper and embed it as a nested login-item bundle.
fn embed_helper(
    root: &Path,
    app: &Path,
    profile: &Profile,
    helper: &Helper,
    icon: &Path,
    signing: &signing::Signing,
) -> Result<()> {
    let Helper {
        component,
        package,
        binary,
        info_plist,
        label,
    } = *helper;
    let sh = Shell::new()?;
    let _repo = sh.push_dir(root);
    println!("==> {label} (build)");
    if profile.release {
        cmd!(sh, "cargo build -p {package} --bin {binary} --release").run()?;
    } else {
        cmd!(sh, "cargo build -p {package} --bin {binary}").run()?;
    }
    let built = profile.dir.join(binary);
    ensure_file(&built)?;

    let bundle_root = component.root(app, CHANNEL);
    fs_err::create_dir_all(bundle_root.join("Contents/MacOS"))?;
    fs_err::create_dir_all(bundle_root.join("Contents/Resources"))?;
    place_binary(
        &built,
        &bundle_root.join("Contents/MacOS").join(binary),
        signing,
    )?;
    fs_err::copy(root.join(info_plist), component.info_plist(app, CHANNEL))
        .with_context(|| format!("could not write the {label} Info.plist"))?;
    fs_err::copy(icon, component.icon(app, CHANNEL))
        .with_context(|| format!("could not copy the app icon into the {label} bundle"))?;
    println!("    embedded {}", bundle_root.display());
    Ok(())
}

/// Put a freshly built executable in the bundle.
///
/// Hardlink where we can — instant, and no 95 MB copy on every run — but a
/// *hard*link, never a symlink: `NSBundle.mainBundle` and Rust's `current_exe`
/// both `realpath()` the executable, and a symlink would resolve back out to
/// `target/debug` and break the bundle association. Signing forces a copy
/// instead: `codesign` rewrites the Mach-O in place, which through a hardlink
/// would rewrite Cargo's own artifact behind its back.
fn place_binary(from: &Path, to: &Path, signing: &signing::Signing) -> Result<()> {
    if to.exists() {
        fs_err::remove_file(to)?;
    }
    if signing.rewrites_binaries() || fs_err::hard_link(from, to).is_err() {
        fs_err::copy(from, to)
            .with_context(|| format!("could not place {} in the bundle", from.display()))?;
    }
    Ok(())
}

fn remove_bundle(path: &Path) -> Result<()> {
    match fs_err::remove_dir_all(path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error.into()),
    }
}

/// Nested helpers first, then the app that seals them: an outer signature
/// covers what is already inside, so signing the app first would invalidate it.
fn sign_order(app: &Path, components: &[Component]) -> Vec<PathBuf> {
    let mut targets: Vec<PathBuf> = components
        .iter()
        .filter(|component| component.nested_bundle(CHANNEL).is_some())
        .map(|component| component.root(app, CHANNEL))
        .collect();
    targets.push(app.to_path_buf());
    targets
}

/// Register the bundle so `openlogi://` resolves to the dev build.
///
/// Dev and release register the same scheme and LaunchServices routes to
/// whichever registered last, so this also re-asserts the dev build after an
/// installed copy has claimed it.
fn register_with_launch_services(app: &Path) -> Result<()> {
    const LSREGISTER: &str = "/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister";
    if !Path::new(LSREGISTER).is_file() {
        return Ok(());
    }
    let sh = Shell::new()?;
    // Not fatal: an unregistered bundle still runs, it just loses deep links.
    if cmd!(sh, "{LSREGISTER} -R {app}")
        .ignore_status()
        .run()
        .is_err()
    {
        println!("    warning: lsregister failed; openlogi:// may open the installed app instead");
    }
    Ok(())
}

/// Whether to build and embed the agent and overlay helpers.
fn helpers_wanted() -> bool {
    std::env::var("OPENLOGI_DEV_AGENT").as_deref() != Ok("0")
}

/// Where cargo put the build, and which profile it was.
///
/// Both come from the binary Cargo handed the runner rather than from
/// `<root>/target`, which `CARGO_TARGET_DIR`, a shared target directory or a
/// git worktree all move somewhere else.
#[derive(Clone, PartialEq, Eq, Debug)]
struct Profile {
    /// The directory the helpers will be built into as well.
    dir: PathBuf,
    /// Whether to pass `--release` when building them. Helpers match the GUI:
    /// a release GUI talking to a debug agent is a confusing thing to debug.
    release: bool,
}

impl Profile {
    fn of(binary: &Path) -> Result<Self> {
        let dir = binary
            .parent()
            .context("the built binary has no parent directory")?;
        let release = match dir.file_name().and_then(|name| name.to_str()) {
            Some("debug") => false,
            Some("release") => true,
            _ => bail!(
                "cannot tell which profile {} was built in — expected its directory to be named debug or release",
                binary.display()
            ),
        };
        Ok(Self {
            dir: dir.to_path_buf(),
            release,
        })
    }
}

#[cfg(test)]
mod tests;
